<?php
/**
 * Script Backup dan Cleanup Data Otomatis
 *
 * Fitur:
 * 1. Backup database sebelum penghapusan
 * 2. Hapus data lama (3 bulan ke atas)
 * 3. Hapus file foto lama
 * 4. Hapus log lama
 * 5. Logging aktivitas backup dan cleanup
 *
 * Cara penggunaan:
 * - Manual: php backup_and_cleanup.php
 * - Otomatis: Setup cron job setiap 3 bulan
 * - Mode backup-only: php backup_and_cleanup.php?mode=backup
 */

// Konfigurasi
date_default_timezone_set('Asia/Makassar');
$config = array(
    'backup_retention_days' => 90, // Backup disimpan 90 hari
    'data_retention_months' => 3,  // Data disimpan 3 bulan
    'log_retention_months' => 6,   // Log disimpan 6 bulan
    'photo_retention_months' => 3, // Foto disimpan 3 bulan
    'backup_dir' => __DIR__ . '/../backups/',
    'max_backup_size_mb' => 100   // Maksimal ukuran backup 100MB
);

// Include database dan logger
require_once __DIR__ . '/../config/database.php';
require_once __DIR__ . '/../config/logger.php';

class BackupCleanup {
    private $db;
    private $logger;
    private $config;
    private $backup_file;
    private $log_messages = array();
    public $mode = 'full';

    public function __construct($database, $config, $mode = 'full') {
        $this->db = $database;
        $this->config = $config;
        $this->logger = new Logger($database);
        $this->mode = $mode;
        // Buat direktori backup jika belum ada
        if (!is_dir($config['backup_dir'])) {
            mkdir($config['backup_dir'], 0755, true);
        }
        $this->backup_file = $config['backup_dir'] . 'backup_' . date('Y-m-d_H-i-s') . '.sql';
    }

    /**
     * Jalankan proses backup dan cleanup
     */
    public function run() {
        $this->log("Memulai proses backup dan cleanup (mode: {$this->mode})...");
        try {
            // 1. Backup database
            $this->backupDatabase();
            if ($this->mode === 'backup') {
                $this->log("Mode backup-only: Lewati proses penghapusan data/foto/log.");
            } else {
                // 2. Cleanup data lama
                $this->cleanupOldData();
                // 3. Cleanup file foto lama
                $this->cleanupOldPhotos();
                // 4. Cleanup log lama
                $this->cleanupOldLogs();
                // 5. Cleanup backup lama
                $this->cleanupOldBackups();
            }
            $this->log("Proses backup dan cleanup selesai.");
            $this->logger->logSystem('info', 'backup_cleanup', 'Backup dan cleanup berhasil (mode: ' . $this->mode . ')', null, 'system');
        } catch (Exception $e) {
            $this->log("Error: " . $e->getMessage());
            $this->logger->logSystem('error', 'backup_cleanup', 'Backup dan cleanup gagal: ' . $e->getMessage(), $e->getTraceAsString(), 'system');
        }
    }

    /**
     * Backup database
     */
    private function backupDatabase() {
        $this->log("Memulai backup database...");

        $tables = array(
            'tbl_absensi', 'tbl_kegiatan', 'tbl_mahasiswa', 'tbl_user',
            'tbl_admin', 'tbl_alasan', 'tbl_setting_absensi', 'tbl_site',
            'tbl_user_logs', 'tbl_auth_logs', 'tbl_attendance_logs',
            'tbl_activity_logs', 'tbl_profile_logs', 'tbl_admin_logs',
            'tbl_system_logs', 'tbl_user_token', 'tbl_pengumuman'
        );

        $backup_content = "-- Backup Database " . date('Y-m-d H:i:s') . "\n";
        $backup_content .= "-- Generated by BackupCleanup Script\n\n";

        foreach ($tables as $table) {
            $this->log("Backup tabel: $table");

            // Get table structure
            $result = mysqli_query($this->db, "SHOW CREATE TABLE $table");
            if ($result) {
                $row = mysqli_fetch_array($result);
                $backup_content .= "\n-- Table structure for $table\n";
                $backup_content .= $row[1] . ";\n\n";

                // Get table data
                $data_result = mysqli_query($this->db, "SELECT * FROM $table");
                if ($data_result && mysqli_num_rows($data_result) > 0) {
                    $backup_content .= "-- Data for $table\n";
                    while ($data_row = mysqli_fetch_assoc($data_result)) {
                        $values = array_map(function($value) {
                            return $value === null ? 'NULL' : "'" . mysqli_real_escape_string($this->db, $value) . "'";
                        }, $data_row);
                        $backup_content .= "INSERT INTO $table VALUES (" . implode(', ', $values) . ");\n";
                    }
                    $backup_content .= "\n";
                }
            }
        }

        // Write backup file
        if (file_put_contents($this->backup_file, $backup_content)) {
            $size = filesize($this->backup_file);
            $this->log("Backup berhasil: " . $this->backup_file . " (" . number_format($size / 1024 / 1024, 2) . " MB)");
        } else {
            throw new Exception("Gagal menulis file backup");
        }
    }

    /**
     * Hapus data lama dari database
     */
    private function cleanupOldData() {
        $this->log("Memulai cleanup data lama...");

        $cutoff_date = date('Y-m-d', strtotime("-{$this->config['data_retention_months']} months"));

        // Hapus absensi lama
        $sql = "DELETE FROM tbl_absensi WHERE tanggal < '$cutoff_date'";
        $result = mysqli_query($this->db, $sql);
        $deleted_absensi = mysqli_affected_rows($this->db);
        $this->log("Hapus $deleted_absensi data absensi lama");

        // Hapus kegiatan lama
        $sql = "DELETE FROM tbl_kegiatan WHERE tanggal < '$cutoff_date'";
        $result = mysqli_query($this->db, $sql);
        $deleted_kegiatan = mysqli_affected_rows($this->db);
        $this->log("Hapus $deleted_kegiatan data kegiatan lama");

        // Hapus alasan lama
        $sql = "DELETE FROM tbl_alasan WHERE tanggal < '$cutoff_date'";
        $result = mysqli_query($this->db, $sql);
        $deleted_alasan = mysqli_affected_rows($this->db);
        $this->log("Hapus $deleted_alasan data alasan lama");
    }

    /**
     * Hapus file foto lama
     */
    private function cleanupOldPhotos() {
        $this->log("Memulai cleanup foto lama...");

        $cutoff_timestamp = strtotime("-{$this->config['photo_retention_months']} months");
        $photo_dirs = array(
            __DIR__ . '/../apps/data_absensi/foto_absen_masuk/',
            __DIR__ . '/../apps/data_absensi/foto_absen_pulang/',
            __DIR__ . '/../apps/mahasiswa/foto/',
            __DIR__ . '/../apps/mahasiswa/bpjs_mahasiswa/',
            __DIR__ . '/../apps/mahasiswa/ktp_mahasiswa/',
            __DIR__ . '/../foto/'
        );

        $deleted_files = 0;
        foreach ($photo_dirs as $dir) {
            if (is_dir($dir)) {
                $files = glob($dir . '*');
                foreach ($files as $file) {
                    if (is_file($file) && filemtime($file) < $cutoff_timestamp) {
                        if (unlink($file)) {
                            $deleted_files++;
                        }
                    }
                }
            }
        }

        $this->log("Hapus $deleted_files file foto lama");
    }

    /**
     * Hapus log lama
     */
    private function cleanupOldLogs() {
        $this->log("Memulai cleanup log lama...");

        $cutoff_date = date('Y-m-d H:i:s', strtotime("-{$this->config['log_retention_months']} months"));

        $log_tables = array(
            'tbl_user_logs', 'tbl_auth_logs', 'tbl_attendance_logs',
            'tbl_activity_logs', 'tbl_profile_logs', 'tbl_admin_logs',
            'tbl_system_logs'
        );

        $total_deleted = 0;
        foreach ($log_tables as $table) {
            $sql = "DELETE FROM $table WHERE created_at < '$cutoff_date'";
            $result = mysqli_query($this->db, $sql);
            $deleted = mysqli_affected_rows($this->db);
            $total_deleted += $deleted;
            $this->log("Hapus $deleted log dari $table");
        }

        $this->log("Total hapus $total_deleted log lama");
    }

    /**
     * Hapus backup lama
     */
    private function cleanupOldBackups() {
        $this->log("Memulai cleanup backup lama...");

        $cutoff_timestamp = strtotime("-{$this->config['backup_retention_days']} days");
        $backup_files = glob($this->config['backup_dir'] . 'backup_*.sql');

        $deleted_backups = 0;
        $total_size = 0;

        foreach ($backup_files as $file) {
            if (is_file($file) && filemtime($file) < $cutoff_timestamp) {
                $size = filesize($file);
                if (unlink($file)) {
                    $deleted_backups++;
                    $total_size += $size;
                }
            }
        }

        $this->log("Hapus $deleted_backups backup lama (" . number_format($total_size / 1024 / 1024, 2) . " MB)");

        // Cek ukuran total backup
        $current_backups = glob($this->config['backup_dir'] . 'backup_*.sql');
        $total_size = 0;
        foreach ($current_backups as $file) {
            $total_size += filesize($file);
        }

        $size_mb = $total_size / 1024 / 1024;
        $this->log("Ukuran total backup: " . number_format($size_mb, 2) . " MB");

        // Jika ukuran backup terlalu besar, hapus yang terlama
        if ($size_mb > $this->config['max_backup_size_mb']) {
            $this->log("Ukuran backup melebihi batas, hapus backup terlama...");
            $this->cleanupOldestBackups($size_mb);
        }
    }

    /**
     * Hapus backup terlama jika ukuran melebihi batas
     */
    private function cleanupOldestBackups($current_size_mb) {
        $backup_files = glob($this->config['backup_dir'] . 'backup_*.sql');

        // Sort by modification time (oldest first)
        usort($backup_files, function($a, $b) {
            return filemtime($a) - filemtime($b);
        });

        foreach ($backup_files as $file) {
            $size = filesize($file);
            if (unlink($file)) {
                $current_size_mb -= ($size / 1024 / 1024);
                $this->log("Hapus backup terlama: " . basename($file));

                if ($current_size_mb <= $this->config['max_backup_size_mb']) {
                    break;
                }
            }
        }
    }

    /**
     * Log pesan
     */
    private function log($message) {
        $timestamp = date('Y-m-d H:i:s');
        $log_message = "[$timestamp] $message";
        echo $log_message . "\n";
        $this->log_messages[] = $log_message;
    }

    /**
     * Dapatkan ringkasan log
     */
    public function getLogSummary() {
        return $this->log_messages;
    }
}

// Ambil mode dari GET/POST/CLI
$mode = 'full';
if (isset($_GET['mode'])) {
    $mode = $_GET['mode'];
} elseif (isset($_POST['mode'])) {
    $mode = $_POST['mode'];
} elseif (php_sapi_name() === 'cli' && isset($argv[1]) && $argv[1] === 'backup') {
    $mode = 'backup';
}

// Jalankan script jika dipanggil langsung
if (php_sapi_name() === 'cli' || isset($_GET['run'])) {
    $backup_cleanup = new BackupCleanup($kon, $config, $mode);
    $backup_cleanup->run();
    if (php_sapi_name() === 'cli') {
        echo "\nRingkasan:\n";
        foreach ($backup_cleanup->getLogSummary() as $log) {
            echo $log . "\n";
        }
    } else {
        echo "<h3>Backup dan Cleanup Selesai</h3>";
        echo "<pre>";
        foreach ($backup_cleanup->getLogSummary() as $log) {
            echo htmlspecialchars($log) . "\n";
        }
        echo "</pre>";
    }
} else {
    echo "<h3>Script Backup dan Cleanup</h3>";
    echo "<p>Script ini akan:</p>";
    echo "<ul>";
    echo "<li>Backup database sebelum penghapusan</li>";
    echo "<li>Hapus data absensi dan kegiatan lebih dari {$config['data_retention_months']} bulan</li>";
    echo "<li>Hapus foto lebih dari {$config['photo_retention_months']} bulan</li>";
    echo "<li>Hapus log lebih dari {$config['log_retention_months']} bulan</li>";
    echo "<li>Hapus backup lebih dari {$config['backup_retention_days']} hari</li>";
    echo "</ul>";
    echo "<p><a href='?run=1&mode=backup' class='btn btn-info'>Backup Saja (Tanpa Hapus Data)</a></p>";
    echo "<p><a href='?run=1' class='btn btn-primary'>Backup & Cleanup (Backup + Hapus Data Lama)</a></p>";
    // Backup otomatis via cron tidak digunakan; jalankan manual dari Admin → Maintenance atau ?run=1 di URL ini.
}
?> 